apiVersion: v2 # K8s related
name: nginx
version: 0.0.2 # --> Chart Version
appVersion: "1.29-trixie" # --> This is application version like catalogue version
description: "Upgrading to 1.29-trixie version"