apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these labels are replicaset labels
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
  annotations:
    kubernetes.io/change-cause: {{.Values.deployment.changeCause}} # This is used to track the changes in deployment, this will be helpful for rollback
spec:
  replicas: {{.Values.deployment.replicas}} # This is the number of pods we want to run, this is also called as desired state
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:{{.Values.deployment.imageVersion}} # This is the image tag, this is also called as application version, this is used to track the changes in application version, this will be helpful for rollback

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 # Container port

