---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  type: "{{.Values.service.type}}" # This is the service type, used to track the changes in service type, this will be helpful for rollback
  selector:
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 # Container port

